spring:
  application:
    name: online-library-system

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: library
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  mail:
    host: smtp.gmail.com
    port: 587
    username: elvinaliyevinfo@gmail.com
    password: yourpassword
    protocol: smtp
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    org.springframework.aop: DEBUG
    az.company.onlinelibrarysystem.aop: INFO
