-- -- Inserting authors
-- INSERT INTO library.author (id, name, biography) VALUES (1, 'J.K. Rowling', 'Author of the Harry Potter series.');
-- INSERT INTO library.author (id, name, biography) VALUES (2, 'George R.R. Martin', 'Author of A Song of Ice and Fire.');
--
-- -- Inserting books with category and language
-- INSERT INTO library.book (id, title, isbn, year_published, category, language)
-- VALUES (1, 'Harry Potter and the Philosopher''s Stone', '9780747532743', 1997, 'Fantasy', 'English');
-- INSERT INTO library.book (id, title, isbn, year_published, category, language)
-- VALUES (2, 'Harry Potter and the Chamber of Secrets', '9780747538493', 1998, 'Fantasy', 'English');
-- INSERT INTO library.book (id, title, isbn, year_published, category, language)
-- VALUES (3, 'A Game of Thrones', '9780553103540', 1996, 'Fantasy', 'English');
--
-- -- Inserting book-author relationships (many-to-many)
-- INSERT INTO library.author_books (author_id, book_id) VALUES (1, 1); -- J.K. Rowling wrote Harry Potter 1
-- INSERT INTO library.author_books (author_id, book_id) VALUES (1, 2); -- J.K. Rowling wrote Harry Potter 2
-- INSERT INTO library.author_books (author_id, book_id) VALUES (2, 3); -- George R.R. Martin wrote A Game of Thrones
